spring:
  cloud:
    gateway:
      routes:
      - id: test1
        uri: https://httpbin.org/
        predicates:
        - Path=/
        - Weight=group1,9
      - id: test2
        uri: https://httpbin.org/
        predicates:
        - Path=/
        - Weight=group1,1
server:
  port: 8088
